package com.iktpreobuka.schoolregister.enumeration;

public enum EMarkDefinition {
	DESCRIPTION_KONTROLNI,
	DESCRIPTION_PISMENI,
	DESCRIPTION_AKTIVNOST,
	DESCRIPTION_ZAKLJUCNA_POLUGODISTE,
	DESCRIPTION_ZAKLJUCNA_KRAJ

}
